In [1]:
import numpy as np
import time
start_time = time.time()

In [2]:
np.random.seed(24787)
a = np.random.randint(0, 8, size=(3,4,4))

In [3]:
print(a)
result_depth1 = np.where(a[0] == 4)
result_depth2 = np.where(a[1] == 4)
result_depth3 = np.where(a[2] == 4)
depth1 = list(zip(result_depth1[0], result_depth1[1]))
depth2 = list(zip(result_depth2[0], result_depth2[1]))
depth3 = list(zip(result_depth3[0], result_depth3[1]))
for cord in depth1:
    print("depth 1 row and column index of value 4:",cord)
for cord in depth2:
    print("depth 2 row and column index of value 4:",cord)
for cord in depth3:
    print("depth 3 row and column index of value 4:",cord)

[[[2 6 4 1]
  [0 4 4 3]
  [6 6 1 2]
  [7 0 6 5]]

 [[1 3 3 7]
  [4 7 2 5]
  [0 4 6 7]
  [5 5 7 1]]

 [[7 2 4 5]
  [6 7 7 0]
  [6 2 0 4]
  [2 0 7 6]]]
depth 1 row and column index of value 4: (0, 2)
depth 1 row and column index of value 4: (1, 1)
depth 1 row and column index of value 4: (1, 2)
depth 2 row and column index of value 4: (1, 0)
depth 2 row and column index of value 4: (2, 1)
depth 3 row and column index of value 4: (0, 2)
depth 3 row and column index of value 4: (2, 3)


In [4]:
b = np.tile(a,(2,2))
print(b.shape)
print(b)

(3, 8, 8)
[[[2 6 4 1 2 6 4 1]
  [0 4 4 3 0 4 4 3]
  [6 6 1 2 6 6 1 2]
  [7 0 6 5 7 0 6 5]
  [2 6 4 1 2 6 4 1]
  [0 4 4 3 0 4 4 3]
  [6 6 1 2 6 6 1 2]
  [7 0 6 5 7 0 6 5]]

 [[1 3 3 7 1 3 3 7]
  [4 7 2 5 4 7 2 5]
  [0 4 6 7 0 4 6 7]
  [5 5 7 1 5 5 7 1]
  [1 3 3 7 1 3 3 7]
  [4 7 2 5 4 7 2 5]
  [0 4 6 7 0 4 6 7]
  [5 5 7 1 5 5 7 1]]

 [[7 2 4 5 7 2 4 5]
  [6 7 7 0 6 7 7 0]
  [6 2 0 4 6 2 0 4]
  [2 0 7 6 2 0 7 6]
  [7 2 4 5 7 2 4 5]
  [6 7 7 0 6 7 7 0]
  [6 2 0 4 6 2 0 4]
  [2 0 7 6 2 0 7 6]]]


In [5]:
c = np.sum(b, axis = 0)

In [6]:
print(c)
print(c.shape)

[[10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]
 [10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]]
(8, 8)


In [7]:
np.random.seed(24787)
a = np.random.randint(0, 10, size=(1000,1000))
b = np.random.randint(0, 10, size=(1000,1000))

In [8]:
def matmul(matrix1,matrix2):
    lst = []
    for row in range(a.shape[0]):
        for col in range(b.shape[1]):
            mat_mul = int(np.dot(a[row],b[:,[col]]))
            lst.append(mat_mul)
    matmul_array = np.asarray(lst)
    result = matmul_array.reshape(a.shape[0],b.shape[1])
    return result

In [9]:
start_time = time.time()
print(matmul(a,b))
end_time = time.time()
print("My matmul function execution time:",end_time - start_time)
print("\n")
start_time = time.time()
print(a@b)
end_time = time.time()
print("Built in matmul function execution time:",end_time - start_time)

[[20248 20350 19789 ... 19680 20445 20500]
 [20929 20833 20719 ... 20444 20891 21227]
 [21194 20950 20565 ... 20130 21208 21259]
 ...
 [20335 20646 20637 ... 20104 20646 20979]
 [19785 19973 19454 ... 19131 20007 19942]
 [20451 20402 20452 ... 19858 20117 20135]]
My matmul function execution time: 6.3232762813568115


[[20248 20350 19789 ... 19680 20445 20500]
 [20929 20833 20719 ... 20444 20891 21227]
 [21194 20950 20565 ... 20130 21208 21259]
 ...
 [20335 20646 20637 ... 20104 20646 20979]
 [19785 19973 19454 ... 19131 20007 19942]
 [20451 20402 20452 ... 19858 20117 20135]]
Built in matmul function execution time: 1.5114598274230957


The function I wrote uses two for loops, one to iterate through the rows of a, one to iterate through the columns of b. This results in a computational complexity of O(n^2). In addition, my code append every dot result in a list and later converts its shape and datatype into the desired format. All of these steps takes extra time, especially the nested for loop.   